import 'dart:io';

class ImportNotesResult {
  final int importedCount;
  final int skippedCount;
  final int failedCount;

  const ImportNotesResult({
    required this.importedCount,
    required this.skippedCount,
    required this.failedCount,
  });
}

abstract class IImportNotesRepository {
  /// Imports notes from a JSON file generated by exportNotesToJsonFile.
  /// Notes whose id already exists locally are skipped.
  /// Media files are not part of the JSON export, so asset paths in imported
  /// notes may point to files which no longer exist on this device.
  Future<ImportNotesResult> importNotesFromJsonFile(File file);
}
